version: '3'
volumes:
  docker:
services:
  database:
    image: mongo
    volumes:
      - docker:/data/db
    ports:
      - 27017:27017

  yobulk:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: yarn dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5050:5050
    environment:
      MONGODB_URI: mongodb://database:27017/yobulk
      DATABASE_NAME: 'yobulk'
      OPENAI_SECRET_KEY: your openai key
      BACKEND_SERVER_HOST: 'http://localhost:5050'
    depends_on:
      - database
