version: '3'
volumes:
  docker:
services:
  database:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - docker:/data/db

  yobulk:
    image: yobulk/yobulk
    ports:
      - 5050:5050
    environment:
      MONGODB_URI: mongodb://database:27017/yobulk
      DATABASE_NAME: 'yobulk'
      OPENAI_SECRET_KEY: your openai key
      BACKEND_SERVER_HOST: 'http://localhost:5050'
    depends_on:
      - database
